### ISSUE TITLE
missing requirements.txt file

### ISSUE THREAD

**Issue by waelsy123** [djeada/Find-your-windows-product-key#1]
I can't find requirements.txt  within the codebase

**Comment by djeada** [comment]
Hello there, stranger.
Thank you for your interest in the project.
This project does not rely on any third-party software or libraries.
Regrettably, I am unable to upload an empty file.

**Comment by waelsy123** [comment]
unfortunately I'm not interest in the project as I have stopped using windows for the last 2 decades, but I was curious how you were doing the trick, awesome job you did there <3

**Comment by djeada** [comment]
When we extend to other operating systems, we will notify you. Would you mind telling us about your area of expertise?

**Comment by waelsy123** [comment]
most doing backend or devops work, generally when it comes to equipments I use mac but I keep most work at my linux server
